name: CI

on: [push]

jobs:
  #build-linux:
  #  name: Build Ubuntu
  #  runs-on: ubuntu-latest
  #  
  #  steps:
  #  - uses: actions/checkout@v1
  #  - name: make build dirs
  #    run: mkdir build_ninja_llvm_ubuntu_debug && mkdir build_ninja_llvm_ubuntu_release && mkdir build_ninja_gcc_ubuntu_debug && mkdir build_ninja_gcc_ubuntu_release
  #  - name: install deps
  #    run: apt install libxcb-image0-dev
  #  - name: cmake configure llvm debug
  #    run: cmake -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ../
  #    working-directory: build_ninja_llvm_ubuntu_debug
  #  - name: cmake configure llvm release
  #    run: cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ../
  #    working-directory: build_ninja_llvm_ubuntu_release
  #  - name: cmake configure gcc debug
  #    run: cmake -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_C_COMPILER=g -DCMAKE_CXX_COMPILER=g++ ../
  #    working-directory: build_ninja_gcc_ubuntu_debug
  #  - name: cmake configure gcc release
  #    run: cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ ../
  #    working-directory: build_ninja_gcc_ubuntu_release
  #  - name: cmake build llvm debug
  #    run: cmake --build build_ninja_llvm_ubuntu_debug
  #  - name: cmake build llvm release
  #    run: cmake --build build_ninja_llvm_ubuntu_release
  #  - name: cmake build gcc debug
  #    run: cmake --build build_ninja_gcc_ubuntu_debug
  #  - name: cmake build gcc release
  #    run: cmake --build build_ninja_gcc_ubuntu_release
      
  build-windows-ninja:
    name: Build Windows Ninja MSVC
    runs-on: windows-latest
    
    steps:
    # Checkout code
    - uses: actions/checkout@v1
    # Install Ninja
    - uses: seanmiddleditch/gha-setup-ninja@v1
    # Setup VS dev env
    - uses: seanmiddleditch/gha-setup-vsdevenv@master

      # Configure Debug
    - name: Configure Ninja MSVC Debug
      run: | # This | is important to inherit the VS dev env
        cmake -GNinja -S. -Bbuild_ninja_msvc_debug -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_CXX_COMPILER=cl
      # Configure Profile
    - name: Configure Ninja MSVC Profile
      run: |
        cmake -GNinja -S. -Bbuild_ninja_msvc_profile -DCMAKE_BUILD_TYPE=RELWITHDEBINFO -DCMAKE_CXX_COMPILER=cl
      # Configure Release
    - name: Configure Ninja MSVC Release
      run: |
        cmake -GNinja -S. -Bbuild_ninja_msvc_release -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_CXX_COMPILER=cl
      
    # Build Debug
    - name: Build Ninja MSVC Debug
      run: cmake --build build_ninja_msvc_debug
    # Build Profile
    - name: Build Ninja MSVC Profile
      run: cmake --build build_ninja_msvc_profile
    # Build Release
    - name: Build Ninja MSVC Release
      run: cmake --build build_ninja_msvc_release
    
  build-windows-vs2019:
    name: Build Windows VS2019 MSVC
    runs-on: windows-latest
  
    steps:
    - uses: actions/checkout@v1
      
    # Config VS2019
    - name: cmake configure vs2019 msvc
      run: cmake -S. -Bbuild_vs2019_msvc
      
    # Build Debug
    - name: cmake build vs2019 msvc debug
      run: cmake --build build_vs2019_msvc --config Debug
    # Build Profile
    - name: cmake build vs2019 msvc profile
      run: cmake --build build_vs2019_msvc --config RelWithDebInfo
    # Build Release
    - name: cmake build vs2019 msvc release
      run: cmake --build build_vs2019_msvc --config Release

